name: Build documentation

on:
  push:
    branches:
      - release
      - doc-builder*

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: course
      path_to_docs: course/chapters/
      additional_args: --not_python_module
      languages: ar bn de en es fa fr gj he hi id it ja ko pt ru th tr vi zh-CN zh-TW
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
